// <auto-generated />
using System;
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaoTrongHieu258.Migrations
{
    [DbContext(typeof(DTH258))]
    [Migration("20240106070119_LopHoc")]
    partial class LopHoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DaoTrongHieu258.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLopHoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLopHoc")
                        .HasColumnType("TEXT");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("DaoTrongHieu258.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoDienThoai")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("DaoTrongHieu258.Models.LopHoc", b =>
                {
                    b.HasOne("DaoTrongHieu258.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
